# Generated by Django 6.0.3 on 2026-03-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number', models.CharField(max_length=75, unique=True, verbose_name='Зав. № машины')),
                ('dvig_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № двигателя')),
                ('transmission_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Зав. № трансмиссии')),
                ('main_bridge_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № ведущего моста')),
                ('controlled_bridge_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Зав. № управляемого моста')),
                ('postavka', models.CharField(blank=True, max_length=250, null=True, verbose_name='Договор поставки №, дата')),
                ('date_of_out', models.DateTimeField(blank=True, null=True, verbose_name='Дата отгрузки с завода')),
                ('usering', models.CharField(blank=True, max_length=250, null=True, verbose_name='Грузополучатель (конечный потребитель)')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='Адрес поставки (эксплуатации)')),
                ('complete_set', models.CharField(blank=True, max_length=250, null=True, verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель машины',
                'verbose_name_plural': 'Документация по эксплуатации моделей машин',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ControlledBridgeModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель управляемого моста',
                'verbose_name_plural': 'Документация по эксплуатации моделей управляемого моста',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DvigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель двигателя',
                'verbose_name_plural': 'Документация по эксплуатации моделей двигателей',
            },
        ),
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Узел отказа',
                'verbose_name_plural': 'Справочник узлов отказа',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainBridgeModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель ведущего моста',
                'verbose_name_plural': 'Документация по эксплуатации моделей ведущего моста',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceOrganisationReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Уполномоченная в ТО организация',
                'verbose_name_plural': 'Справочник уполномоченных в ТО организаций',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отказа')),
                ('time_work', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Наработка, м/час')),
                ('failure_description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Oтказа')),
                ('parts_used', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Используемые запасные части')),
                ('date_of_restoration', models.DateTimeField(blank=True, null=True, verbose_name='Дата восстановления')),
                ('equipment_downtime', models.IntegerField(default=0, verbose_name='Время простоя техники (Часов)')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ восстановления',
                'verbose_name_plural': 'окументация способов восстановления',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, verbose_name='Дата проведения ТО')),
                ('time_work', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Наработка, м/час')),
                ('order_number', models.CharField(max_length=100, unique=True, verbose_name='№ заказ-наряда')),
                ('order_date', models.DateTimeField(verbose_name='Дата заказ-наряда')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransmissionModelReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Модель')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Модель трансмиссии',
                'verbose_name_plural': 'Документация по эксплуатации моделей трансмиссий',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeOfMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Вид ТО')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид технического обслуживания',
                'verbose_name_plural': 'Документация видов ТО',
                'abstract': False,
            },
        ),
    ]
