# Generated by Django 6.0.3 on 2026-03-04 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarInfo', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_machine', to='accounts.users', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.users', verbose_name='Cервисная компания'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Car_model', to='CarInfo.carmodelreference', verbose_name='Модель машины'),
        ),
        migrations.AddField(
            model_name='car',
            name='controlled_bridge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controlled_bridge_model', to='CarInfo.controlledbridgemodelreference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='car',
            name='dvig_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Dvig_model', to='CarInfo.dvigmodel', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='car',
            name='main_bridge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_bridge_model', to='CarInfo.mainbridgemodelreference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='Car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='CarInfo.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_node', to='CarInfo.failurenode', verbose_name='Oтказа'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_method', to='CarInfo.recoverymethod', verbose_name='Способ восстановления'),
        ),
        migrations.AddField(
            model_name='to',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TO', to='CarInfo.car', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='car',
            name='transmission_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmission_model', to='CarInfo.transmissionmodelreference', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='to',
            name='type_of_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_maintenance', to='CarInfo.typeofmaintenance', verbose_name='Вид технического обслуживания'),
        ),
    ]
